site_name: My Docs
site_name: XIN SHEN

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://fonts.googleapis.com/css2?family=Fira+Sans&display=swap

extra_css:
  - stylesheets/custom.css


nav:
  - Home: index.md
  - Blog: 
        
        - NP-hard/Notebook: blog/Np.md
        - ICA_väst/Swedish: blog/ica_1.md
        - Stirling number/Notebook: blog/Stirling_Number.md
        - 随笔1: blog/bi1.md
        - 随笔2: blog/bi2.md
        - 随笔3: blog/bi3.md
        - 随笔4-玄学: blog/bi4.md
        - 随笔5: blog/bi5.md
        - 随笔6-对小型动态网络中能量是否守恒的简单思考: blog/bi6.md
        - 随笔7: blog/bi7.md
        - 随笔8: blog/bi8.md
        
        
   
          

    

theme:
  palette:
    primary: teal
    accent: brown
  logo: F.png

  name: material
  features:
    - navigation.path
    - navigation.tabs
    - navigation.instant
extra:
  homepage: https://xins3.github.io/


