site_name: My Docs
site_name: XIN SHEN

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://fonts.googleapis.com/css2?family=Fira+Sans&display=swap

extra_css:
  - stylesheets/custom.css


nav:
  - Home: index.md
  - Blog: 
        
        - NP-hard/Notebook: blog/Np.md
        - ICA_väst/Swedish: blog/ica_1.md
        - Stirling number/Notebook: blog/Stirling_Number.md
   
          

    

theme:
  palette:
    primary: teal
    accent: brown
  logo: w1.HEIC

  name: material
  features:
    - navigation.path
    - navigation.tabs
    - navigation.instant
extra:
  homepage: https://xins3.github.io/


