site_name: My Docs
site_name: XIN SHEN

nav:
  - Home: index.md
  - Blog: 
        
        - NP-hard/Notebook: blog/Np.md
        - ICA_väst/Swedish: blog/ica_1.md
   
          

    

theme:
  palette:
    primary: teal
    accent: brown
  logo: ele.png

  name: material
  features:
    - navigation.path
    - navigation.tabs
    - navigation.instant
extra:
  homepage: https://xins3.github.io/


